ESP/ESP/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path("" , include('gestion.urls')),
    path('admin/', admin.site.urls),
]

ESP/gestion/urls.py
from django.urls import path
from . import views
urlpatterns = [
 	path('',views.home ,name='home'), 
 	path('gestion_etudiant.html/',views.gestion_etudiant ,name='gestion_etudiant'),
 	path('gestion_departement.html/',views.gestion_departement ,name='gestion_departement'),
 	path('gestion_modules.html/',views.gestion_modules ,name='gestion_modules'),
            path('listEtudiants/', views.EtudiantsList.as_view(), name= 'index' ),
            path('listDepartement/', views.DepartementsList.as_view(), name= 'departementlist' ),
    path('ajouterEtudiant/', views.EtudiantsCreate.as_view(), name= 'add' ),
    path('etudiant/<int:matricule>/', views.EtudiantDetailView.as_view(), name='etudiant_detail'),
    path('etudiant/<int:matricule>/modifier/', views.EtudiantUpdate.as_view(), name='etudiant-update'),
    path('etudiant/delete/<int:pk>/', views.EtudiantDeleteView.as_view(), name='etudiant-delete'),
    #path('etudiant/search/', views.EtudiantSearchView.as_view(), name='rechercher_etudiant'),
    path('etudiant/recherche/', views.EtudiantRechercheView.as_view(), name='recherche_etudiant'),
path('departement/ajouter/', views.DepartementCreate.as_view(), name='departement_create'),
    path('departement/modifier/<str:nom>/', views.DepartementUpdate.as_view(), name='departement_update'),
    path('departement/supprimer/<str:nom>/', views.DepartementDelete.as_view(), name='departement_delete'),
    path('departement/<str:nom>/', views.DepartementEtudiants.as_view(), name='departement_etudiants'), 
    
    path('elementmodule/ajouter/', views.ElementModuleCreate.as_view(), name='elementmodule_create'),
    path('elementmodule/modifier/<int:pk>/', views.ElementModuleUpdate.as_view(), name='elementmodule_update'),
path('elementmodule/supprimer/<int:pk>/', views.ElementModuleDelete.as_view(), name='elementmodule_delete'),

     path('note/ajouter/', views.NoteCreate.as_view(), name='note_create'),
    path('note/modifier/<int:pk>/', views.NoteUpdate.as_view(), name='note_update'),
    path('note/supprimer/<int:pk>/', views.NoteDelete.as_view(), name='note_delete'),
    path('note/liste/<str:departemen>', views.NoteList.as_view(), name='note_list'),

]

ESP/gestion/models.py
from django.db import models
from django.core.validators import MinValueValidator

class Departement(models.Model):
    nom = models.CharField(max_length=50)
    code = models.CharField(max_length=10)

    def __str__(self):
        return self.nom

class ElementModule(models.Model):
    code = models.CharField(max_length=10,unique=True)
    nom = models.CharField(max_length=100,unique=True)
    departement = models.ForeignKey(Departement, on_delete=models.CASCADE)
    coefficient = models.IntegerField(validators=[MinValueValidator(1)])
    credit = models.IntegerField(validators=[MinValueValidator(1)])

    def __str__(self):
        return self.nom


class Etudiant(models.Model):
    nom = models.CharField(max_length=50)
    prenom = models.CharField(max_length=50)
    date_de_naissance = models.DateField(help_text = "\nPlease use the following format: <em>YYYY-MM-DD</em>.",)
    lieu_de_naissance = models.CharField(max_length=100)
    pays_de_naissance = models.CharField(max_length=100)
    departement = models.ForeignKey(Departement, on_delete=models.CASCADE, blank=True)
    voie_acces = models.CharField(max_length=50, choices=[('voie1', 'Voie 1'), ('voie2', 'Voie 2'), ('reorientation', 'Réorientation')])
    matricule = models.IntegerField(validators=[MinValueValidator(10000)], unique=True, blank=True)
    nationalite = models.CharField(max_length=50)
    identifiant_national = models.IntegerField(null=True)

    statut = models.CharField(max_length=10, choices= [
        ('Etudiant', 'Etudiant'),
        ('dipme', 'Diplômé'),
        ('renvoyé', 'Renvoyé'),
        ('DD', 'DD'),
        ('échange', 'Échange'),
        ('cénsure', 'Césure'),
        ('abandon', 'Abandon'),
    ])
    annee_inscription = models.IntegerField(blank=True)
   
   
    def __str__(self):
    	return self.prenom+" "+self.nom
    def get_absolute_url(self):
        return reverse('etudiant_detail', args=[str(self.id)])


class Note(models.Model):
    etudiant = models.ForeignKey(Etudiant, on_delete=models.CASCADE)
    departement = models.ForeignKey(Departement, on_delete=models.CASCADE)
    element_module = models.ForeignKey(ElementModule, on_delete=models.CASCADE)
    note = models.DecimalField(max_digits=5, decimal_places=2,unique=True)

    def __str__(self):
        return f"Note de {self.etudiant} pour {self.element_module}"

ESP/gestion/forms.py
from django import forms
from .models import Departement, Etudiant

class EtudiantsCreateForm(forms.ModelForm):
    departement = forms.ModelChoiceField(queryset=Departement.objects.all(), empty_label=None)

    class Meta:
        model = Etudiant
        fields = '__all__'

ESP/gestion/views.py
from django.shortcuts import render,HttpResponse
from django.views.generic import *
from .models import *
from django.urls import reverse_lazy
from reportlab.pdfgen import canvas
from .forms import EtudiantsCreateForm
#from docx import Document
from reportlab.lib.pagesizes import letter
# Create your views here.
def home(request):
	return render(request,'gestion/home.html')
def gestion_etudiant(request):
	return render(request,'gestion/gestion_etudiant.html')
def gestion_departement(request):
	return render(request,'gestion/gestion de departement.html')
def gestion_modules(request):
	return render(request,'gestion/gestion de elements modules.html')
class DepartementCreate(CreateView):
    model = Departement
    fields = ['nom', 'code']
    success_url = reverse_lazy('home')
    template_name = 'gestion/departement_create.html'

class DepartementUpdate(UpdateView):
    model = Departement
    fields = ['nom', 'code']
    success_url = reverse_lazy('home')
    template_name = 'gestion/departement_update.html'
    def get_object(self, queryset=None):
        nom = self.kwargs.get('nom')
        return self.model.objects.get(nom=nom)
class DepartementDelete(DeleteView):
    model = Departement
    success_url = reverse_lazy('home')
    template_name = 'gestion/departement_confirm_delete.html'
    def get_object(self, queryset=None):
        nom = self.kwargs.get('nom')
        return self.model.objects.get(nom=nom)
class DepartementEtudiants(ListView):
    model = Etudiant
    template_name = 'gestion/liste_etudiants_departement.html'
    context_object_name = 'etudiants'
    def get_object(self, queryset=None):
        context = super().get_context_data(**kwargs)
        etudiants = self.object
        modules = ElementModule.objects.filter(departement=nom)
        context['modules'] = modules
        return context
class DepartementsList(ListView):
    model = Departement
    template_name='gestion/liste_departements.html'
    context_object_name = 'departements'
    


    def get_object(self, queryset=None):
        nom = self.kwargs.get('nom')
        return self.model.objects.get(nom=nom)

	
class EtudiantsCreate(CreateView):
    model = Etudiant
    template_name = 'gestion/inscription_Etudiant.html'
    form_class = EtudiantsCreateForm
    success_url = '../ajouterEtudiant'

class EtudiantsList(ListView):
    model = Etudiant
    template_name='gestion/liste_etudiants.html'
    context_object_name = 'etudiants'
class EtudiantDetailView(DetailView):
    model = Etudiant
    template_name = 'gestion/etudiant_detail.html'
    context_object_name = 'etudiant'


    def generate_certificat_inscription(self):
	    etudiant = self.get_object()

	    with open("gestion/templates/template_inscription.txt", "r") as file:
	    	contenu = file.read()
	    contenu_rempli = contenu.replace("[NOM de l'étudiant]", etudiant.nom)
	    contenu_rempli = contenu_rempli.replace("[Prénom de l'étudiant]", etudiant.prenom)
	    contenu_rempli = contenu_rempli.replace("[Date de naissance]", str(etudiant.date_de_naissance))
	    contenu_rempli = contenu_rempli.replace("[Lieu de naissance]", str(etudiant.lieu_de_naissance))
	    contenu_rempli = contenu_rempli.replace("[Département (optionnel)]", str(etudiant.departement))
	    contenu_rempli = contenu_rempli.replace("[Voie d'accès]", etudiant.voie_acces)
	    contenu_rempli = contenu_rempli.replace("[Matricule]", str(etudiant.matricule))
	    contenu_rempli = contenu_rempli.replace("[Nationalité]", etudiant.nationalite)
	    contenu_rempli = contenu_rempli.replace("[NNI ou Numéro de passeport]", str(etudiant.identifiant_national))
	    contenu_rempli = contenu_rempli.replace("[Statut]", etudiant.statut)

	    # Générer le PDF avec le texte rempli
	    #contenu_rempli = contenu_rempli[1:]
	    pdf_filename = f"certificat_inscriptionde_{etudiant.matricule}.pdf"
	    pdf_canvas = canvas.Canvas(pdf_filename,pagesize=letter)
	    pdf_canvas.setFont("Helvetica", 10)
	    logo_path = "static/images/logo.jpg"
	    pdf_canvas.drawImage(logo_path, 250, 700, width=100, height=100)
	    
	    lignes = contenu_rempli.split("\n")
	    y = 700
	    for ligne in lignes:
        	    pdf_canvas.drawString(100, y, ligne)
        	    y -= 15
	    pdf_canvas.showPage()
	    pdf_canvas.save()

	    with open(pdf_filename, 'rb') as file:
	    	response = HttpResponse(file.read(), content_type='application/pdf')
	    	response['Content-Disposition'] = f'attachment; filename="{pdf_filename}"'

	    return response

    def get(self, request, *args, **kwargs):
        if 'download' in request.GET:
            # Télécharge le certificat d'inscription
            return self.generate_certificat_inscription()
        else:
            # Affiche les détails de l'étudiant
            return super().get(request, *args, **kwargs)
        
    def get_object(self, queryset=None):
        matricule = self.kwargs.get('matricule')
        return self.model.objects.get(matricule=matricule)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        etudiant = self.object
        modules = ElementModule.objects.filter(departement=etudiant.departement)
        notes = Note.objects.filter(etudiant=etudiant)
        context['notes'] = notes
        context['modules'] = modules
        return context
class EtudiantUpdate(UpdateView):
    model = Etudiant
    template_name = 'gestion/etudiant_update.html'
    fields = '__all__'
    success_url = '../'
    def get_object(self, queryset=None):
        matricule = self.kwargs.get('matricule')
        return self.model.objects.get(matricule=matricule)
class EtudiantDeleteView(DeleteView):
    model = Etudiant
    #template_name = 'gestion/etudiant-delete.html'
    success_url = reverse_lazy('home')
    	
class EtudiantRechercheView(ListView):
    model = Etudiant
    template_name = 'gestion/recherche_etudiant.html'  # Le nom du template de recherche

    def get_queryset(self):
        queryset = super().get_queryset()

        # Récupérer les paramètres de recherche depuis la requête GET
        nni = self.request.GET.get('nni')
        matricule = self.request.GET.get('matricule')
        date_naissance = self.request.GET.get('date_naissance')
        nom = self.request.GET.get('nom')

        # Appliquer les filtres de recherche aux étudiants
        if nni:
            queryset = queryset.filter(identifiant_national=nni)
            queryset = queryset.filter(identifiant_national__contains =nni)
        if matricule:
            queryset = queryset.filter(matricule__contains =matricule)
        if date_naissance:
            queryset = queryset.filter(date_de_naissance__contains =date_naissance)
        if nom:
            queryset = queryset.filter(nom__icontains = nom)

        return queryset

class ElementModuleCreate(CreateView):
    model = ElementModule
    template_name = 'gestion/elementmodule_create.html'
    fields = ['code', 'nom', 'departement', 'coefficient', 'credit']
    success_url = reverse_lazy('home')

class ElementModuleUpdate(UpdateView):
    model = ElementModule
    template_name = 'gestion/elementmodule_update.html'
    fields = ['code', 'nom', 'departement', 'coefficient', 'credit']
    success_url = reverse_lazy('home')

class ElementModuleDelete(DeleteView):
    model = ElementModule
    template_name = 'gestion/elementmodule_confirm_delete.html'
    success_url = reverse_lazy('home')

class NoteCreate(CreateView):
    model = Note
    template_name = 'gestion/note_create.html'
    fields = ['etudiant', 'departement', 'element_module', 'note']
    success_url = reverse_lazy('home')

class NoteUpdate(UpdateView):
    model = Note
    template_name = 'gestion/note_update.html'
    fields = ['etudiant', 'departement', 'element_module', 'note']
    success_url = reverse_lazy('home')

class NoteDelete(DeleteView):
    model = Note
    template_name = 'gestion/note_confirm_delete.html'
    success_url = reverse_lazy('home')

class NoteList(ListView):
    model = Note
    template_name = 'gestion/note_list.html'
    context_object_name = 'notes'
    def get_object(self, queryset=None):
        	departemen = self.kwargs.get('departemen')
        	return self.model.objects.get(departemen=departemen)

ESP/gestion/templates/gestion/departement_create.html
  <h2>Ajouter un département</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Enregistrer</button>
  </form>

ESP/gestion/templates/gestion/departement_detail.html
<!-- templates/departement_detail.html -->
<!DOCTYPE html>
<html>
<head>
    <title>Détails du département</title>
</head>
<body>
    <h1>Détails du département {{ departement.nom }}</h1>
    <h2>Liste des étudiants</h2>
    <ul>
        {% for etudiant in etudiants %}
        <li>{{ etudiant.nom }} {{ etudiant.prenom }}</li>
        {% endfor %}
    </ul>
    <h2>Liste des enseignants</h2>
    <ul>
        {% for enseignant in enseignants %}
        <li>{{ enseignant.nom }} {{ enseignant.prenom }}</li>
        {% endfor %}
    </ul>
    <h2>Liste des modules</h2>
    <ul>
        {% for module in modules %}
        <li>{{ module.nom }}</li>
        {% endfor %}
    </ul>
</body>
</html>

ESP/gestion/templates/gestion/departement_update.html
<h2>Modifier un département</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Modifier</button>
  </form>

ESP/gestion/templates/gestion/elementmodule_confirm_delete.html
<h1>Supprimer un élément de module</h1>
  <p>Êtes-vous sûr de vouloir supprimer cet élément de module ?</p>
  <form method="post">
    {% csrf_token %}
    <button type="submit">Confirmer la suppression</button>
  </form>

ESP/gestion/templates/gestion/elementmodule_create.html
 <h1>Ajouter un élément de module</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Enregistrer</button>
  </form>

ESP/gestion/templates/gestion/elementmodule_update.html
  <h1>Modifier un élément de module</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Enregistrer</button>
  </form>

ESP/gestion/templates/gestion/etudiant_confirm_delete.html
{% extends 'gestion/main.html' %}
{% load static %}

{% block additional_styles %}<link rel="stylesheet"  href="{% static "/css/supprimer.css" %}">{% endblock %}
    
    {% block title %}confirmer la supprimation de l'étudiant {{ etudiant.prenom }} {{ etudiant.nom }}  {{ etudiant.matricule }} {% endblock %}
    
 {% block content %}
  <h2>Suppression de l'étudiant</h2>

  <p>Êtes-vous sûr de vouloir supprimer l'étudiant {{ object.nom }} {{ object.prenom }} (matricule: {{ object.matricule }}) ?</p>

  <form method="POST">
    {% csrf_token %}
    <button type="submit" onclick="return confirm('Êtes-vous sûr de vouloir supprimer cet étudiant ?')">Confirmer la suppression</button>
    <a href="{% url 'etudiant_detail' matricule=object.matricule %}"  >Annuler</a>
  </form>
  
  {% endblock content %}
  

ESP/gestion/templates/gestion/etudiant_detail.html
{% extends 'gestion/main.html' %}
{% load static %}

{% block additional_styles %}<link rel="stylesheet"  href="{% static "/css/etudiant_detail.css" %}">{% endblock %}

    




{% block title %}Détails de l'étudiant {{ etudiant.prenom }} {{ etudiant.nom }}  {{ etudiant.matricule }} {% endblock %}
    
 {% block content %}

 <style>
 h2{
 color:black;}
 
img{
height:150px;
width:150px;
padding-left:200px;
}
body {
  background-color: #f1f1f1; /* Couleur de fond de la page */
  color: #333333; /* Couleur du texte dans la page */
}

 </style>
 <div class=content>
    <h1>Détails de l'étudiant</h1>
    <h2>{{ etudiant.prenom }} {{ etudiant.nom }}</h2>
    <ul>
        <li>Date de naissance: {{ etudiant.date_de_naissance | date:"d-m-Y"}}</li>
        <li>Lieu de naissance: {{ etudiant.lieu_de_naissance }}</li>
        <li>Pays de naissance: {{ etudiant.pays_de_naissance }}</li>
        <li>Département: {{ etudiant.departement }}</li>
        <li>Voie d'accès: {{ etudiant.get_voie_acces_display }}</li>
        <li>Matricule: {{ etudiant.matricule }}</li>
        <li>Nationalité: {{ etudiant.nationalite }}</li>
        <li>Identifiant national: {{ etudiant.identifiant_national }}</li>
        <li>Statut: {{ etudiant.statut }}</li>
        <li>Année d'inscription: {{ etudiant.annee_inscription }}</li>
    </ul>
    
<div class=immg>
    <a  href="{% url 'etudiant-update' matricule=etudiant.matricule %}" ><img src="{% static "/images/modification.png" %}"  alt="modification" ></a>
 
    <a  href="{% url 'etudiant-delete' pk=etudiant.id %}" onclick="return confirm('Êtes-vous sûr de vouloir supprimer cet étudiant ?')"><img src="{% static "/images/supprimer.jpg" %}"  alt="supprimer" ></a>

<a  href="{% url 'etudiant_detail' etudiant.matricule %}?download=1">
 <img src="{% static "/images/telechargement.jpg" %}" alt="Télécharger le certificat d'inscription"></a>
</div>
    
<br>
<!-- Reste du template... -->

<h3>Modules</h3>
<table>
    <thead>
        <tr>
            <th>Module</th>
            <th>Note</th>
        </tr>
    </thead>
    <tbody>
        {% for module in modules %}
        <tr>
            <td>{{ module.nom }}</td>
            <td>
                {% for note in notes %}
                    {% if note.element_module == module %}
                        {{ note.note }}
                    {% endif %}
                {% empty %}
                    Non saisi
                {% endfor %}
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

<!-- Reste du template... -->

 {% endblock content %}

ESP/gestion/templates/gestion/etudiant_update.html
<h2>Modification des données d'un étudiant</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" onclick="return confirm('Êtes-vous sûr de vouloir modifier les données de cet étudiant ?')">Enregistrer les modifications</button>
  </form>
  

ESP/gestion/templates/gestion/gestion de departement.html
{% extends 'gestion/main.html' %}
{% block title %}gestion des departement{% endblock %}
{% block content %}
<!DOCTYPE html>
<html>
<head>
    <title>Dashboard</title>
    <style>
        .add-button {
            background-color: green;
            color: white;
        }

        .list-button {
            background-color: blue;
            color: white;
        }
    </style>
</head>
<body>
    <h1>Dashboard</h1>

    <button class="add-button" onclick="location.href='{% url 'departement_create' %}'">Ajouter une departement</button>
    <button class="list-button" onclick="location.href='{% url 'departementlist' %}'">Liste des departements</button>
</body>
</html>
 {% endblock content %}

ESP/gestion/templates/gestion/home.html
{% extends 'gestion/main.html' %}
{% load static %}

{% block title %}Accueil - Gestion de la scolarité ESP{% endblock %}

{% block content %}
<div class="hom">
    <h1>Bienvenue sur le système de gestion de la scolarité</h1>
    <h2>École Supérieure Polytechnique (ESP)</h2>

    <p>Bienvenue sur la plateforme de gestion de la scolarité de l'École Supérieure Polytechnique (ESP). Cette application vous permet de gérer facilement les informations et les opérations liées à la scolarité des étudiants.</p>

    <h3>Fonctionnalités de l'application :</h3>
    <ul>
        <li>Gestion des étudiants : ajout, modification et suppression d'étudiants</li>
        <li>Gestion des cours : création, modification et suppression de cours</li>
        <li>Gestion des inscriptions : inscription et désinscription des étudiants aux cours</li>
        <li>Génération de certificats d'inscription</li>
        <li>Consultation des informations des étudiants</li>
    </ul>

    <p>Utilisez le menu de navigation pour accéder aux différentes fonctionnalités de l'application.</p>

    <p>En cas de problème ou de besoin d'assistance, <a href="#"> contacter le service d'assistance de l'école.</p></a>
</div>
    <img class='logo0' src="{% static '/images/logo.jpg' %}" alt="Logo ESP">

{% endblock content %}

ESP/gestion/templates/gestion/liste_departements.html
{% extends 'gestion/main.html' %}
{% load static %}

  {% block title %}Liste des étudiants{% endblock %}
    {% block content %}
    
    <link rel="stylesheet"  href="{% static '/css/liste_etudiants.css' %}">
    
    <h1>Liste des étudiants</h1>
	    <table >
        
          <thead>
    <tr>
      <th >nom</th>
      <th >code</th>
      <th >voir details</th>
      <th >modification</th>
      <th >supprimation</th>
    </tr>
  </thead>
  {% for departement in departements %}
  <tbody>
      <td>{{ departement.nom | capfirst}}</td>
      <td>{{ departement.code | capfirst}}</td>
      <td><a href="{% url 'departement_etudiants' nom=departement.nom  %}">᪠ voir plus</a></td>
          <td><a  href="{% url 'departement_update' nom=departement.nom %}" >modification</a></td>
 
    <td><a  href="{% url 'departement_delete' nom=departement.nom %}" onclick="return confirm('Êtes-vous sûr de vouloir supprimer cet étudiant ?')">supprimer</a></td>

    </tr>

            
        {% empty %}
            <li>Aucun étudiant enregistré</li>
        {% endfor %}
  </tbody>



        {% endblock content %}

ESP/gestion/templates/gestion/note_update.html
  <h2>Modifier une note</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Enregistrer</button>
  </form>

ESP/gestion/templates/gestion/recherche_etudiant.html
{% extends 'gestion/main.html' %}
{% load static %} 
{% block title %}Liste des étudiants{% endblock %}
{% block content %}


<a href="{% url 'recherche_etudiant' %}"><h2>← liste des etudiants</h2></a>
    
    <link rel="stylesheet"  href="{% static '/css/liste_etudiants.css' %}">
    <form method="get" action="">
    <input type="number" name="nni" placeholder="NNI">
    <input type="number" name="matricule" placeholder="Matricule">
    <input type="date" name="date_naissance" placeholder="Date de naissance">
    <input type="text" name="nom" placeholder="Nom">
    <button type="submit">Rechercher</button>
</form>
</head>
<body>
    <h1>Liste des étudiants</h1>
	    <table >
        
          <thead>
    <tr>
      <th >nom</th>
      <th >prenom</th>
      <th >matricule</th>
      <th >voir details</th>
    </tr>
  </thead>
  {% for etudiant in object_list %}
  <tbody>
      <td>{{ etudiant.nom | capfirst}}</td>
      <td>{{ etudiant.prenom | capfirst}}</td>
      <td>{{etudiant.matricule}}</td>
      <td><a href="{% url 'etudiant_detail' matricule=etudiant.matricule  %}">᪠ voir plus</a></td>
    </tr>

            
        {% empty %}
            <li>Aucun étudiant enregistré</li>
        {% endfor %}
  </tbody>


        {% endblock content %}
</body>
</html>